### ISSUE TITLE
it doesn't work with proxy socks v5

### ISSUE THREAD

**Issue by masafaga** [BiglySoftware/BiglyBT-plugin-mlDHT#3]
Hello!
Can someone implement an option to push mainline dht plugin (49001 UDP) to proxy socks v5(127.0.0.1), it's doesn't work by default.
I'm using google translate.
Regards,

**Comment by parg** [comment]
You'd need to raise that as an issue on the underlying mlDHT project - https://github.com/the8472/mldht

**Comment by masafaga** [comment]
thank you!
